export const HOBBY_ALREADY_EXISTS = 'Hobby already exists'
export const COULD_NOT_CREATE_HOBBY = 'Could not create hobby'
export const HOBBY_NOT_FOUND = 'Hobby not found'
export const COULD_NOT_ATTACH_HOBBY_TO_USER = 'Could not attach hobby to user'
export const COULD_NOT_GET_HOBBIES = 'Could not get hobbies'