export const FAILED_TO_CREATE_PARTY = 'Failed to create party'
export const USER_HAS_NO_ADDRESS = 'User has no address'
export const COULD_NOT_GET_PARTIES = 'Could not get parties'
export const USER_DOES_NOT_EXIST = 'User does not exist'
export const PARTY_DOES_NOT_EXIST = 'Party does not exist'
export const USER_IS_NOT_HOST = 'User is not host'
export const FAILED_TO_UPDATE_PARTY = 'Failed to update party'
export const COULD_NOT_GET_PARTY = 'Could not get party'
